name: 'Build'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v2.1.5'
        with:
          node-version: '14.x'

      - run: 'npm install --global npm@7'

      - name: 'Install'
        run: 'npm ci'

      - name: 'Build Package'
        run: 'npm run build'

      - name: 'Build Example'
        run: 'cd example && npm ci && npm run build -- --public-url "https://divlo.github.io/react-component-form/"'
