name: 'Test'

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v2'

      - name: 'Use Node.js'
        uses: 'actions/setup-node@v2.1.5'
        with:
          node-version: '14.x'

      - run: 'npm install --global npm@7'

      - name: 'Install'
        run: 'npm ci --cache .npm --prefer-offline'

      - name: 'Test'
        run: 'npm run test'
